In [1]:
import numpy as np
r1=np.add.reduce([1,2,3])#reduce()它沿着axis指定的轴对数组进行操作,输出的结果是1+2+3=6

In [2]:
r1

6

In [3]:
r2=np.add.reduce([[1,2,3],[4,5,6]],axis=1)#输出两个
r2

array([ 6, 15])

In [5]:
r3=np.add.accumulate([1,2,3])#accumulate()函数输出的是与输入数组形状相同，保留所有中间计算结果
r3

array([1, 3, 6])

In [6]:
r4=np.add.accumulate([[1,2],[4,5],[7,8]],axis=1)

In [7]:
r4

array([[ 1,  3],
       [ 4,  9],
       [ 7, 15]])

In [9]:
r5=np.add.reduce([[1,1,1],[2,2,2],[3,3,3]],axis=0)#axis=0是指按行，axis=1是指按列
r5

array([6, 6, 6])

In [10]:
a=np.array([1,2,3,4])
result=np.add.reduceat(a,indices=[0,1,0,2,0,3,0])
result

array([ 1,  2,  3,  3,  6,  4, 10])

In [11]:
np.multiply.outer([1,2,3,4,5],[2,3,4])

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16],
       [10, 15, 20]])

# 多维数组下的下标存取

In [13]:
a=np.arange(3*4*5).reshape(3,4,5)
lidx=[[0],[1]]
aidx=np.array(lidx)

In [17]:
a[lidx]

array([[5, 6, 7, 8, 9]])

In [18]:
a[aidx]

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])

# 函数库
## 随机数

In [19]:
from numpy import random as nr
np.set_printoptions(precision=2)
r1=nr.rand(4,3)#产生0到1的随机浮点数，组成一个四乘三矩阵
r2=nr.randn(4,3)#产生标准正态分布随机数
r3=nr.randint(0,10,(4,3))#产生指定范围内的随机整数，包括起始值，但不包括终值

In [20]:
r1

array([[ 0.22,  0.8 ,  0.67],
       [ 0.13,  0.08,  0.51],
       [ 0.73,  0.22,  0.13],
       [ 0.14,  0.91,  0.35]])

In [21]:
r2

array([[ 0.49,  1.12, -0.33],
       [-0.79, -0.34,  0.89],
       [-0.23,  0.19, -1.56],
       [-1.1 , -0.22, -1.51]])

In [22]:
r3

array([[8, 2, 4],
       [4, 3, 2],
       [5, 2, 3],
       [3, 6, 1]])

In [23]:
a1=nr.normal(100,10,(4,3))#正态分布，前两个值是期望值和标准差，后面产生数组的形状
a2=nr.uniform(10,20,(4,3))#均匀分布，前两个参数是起始值和终值
a3=nr.poisson(2.0,(4,3))#泊松分布，第一个参数指定系数

In [25]:
a1

array([[  95.31,   98.18,   93.03],
       [ 102.43,  101.58,  101.36],
       [ 104.38,  104.98,   90.58],
       [ 100.61,   82.04,   98.1 ]])

In [26]:
a2

array([[ 18.83,  18.2 ,  13.52],
       [ 10.19,  13.99,  18.87],
       [ 17.61,  11.88,  19.82],
       [ 11.38,  18.46,  16.64]])

In [27]:
a3

array([[4, 2, 4],
       [1, 2, 3],
       [5, 0, 1],
       [2, 2, 3]])

In [29]:
a=np.array([1,2,3,4,5,6])
b=nr.permutation(a)#产生随机排列后的数列
b

array([5, 1, 3, 2, 6, 4])

In [30]:
c=nr.permutation(10)#产生【0,10）这10个整数的随机排列

In [31]:
c

array([7, 9, 5, 1, 2, 6, 3, 0, 8, 4])

In [33]:
print (nr.permutation(10))

[8 6 9 3 5 7 0 1 2 4]


In [34]:
nr.shuffle(a)#直接将参数数组打乱
a

array([6, 3, 1, 5, 4, 2])

In [36]:
a=np.arange(10,25,dtype=float)
c1=nr.choice(a,size=(3,3))#choice()函数在指定样本中随机抽取，size表示输出数组的形状，replace为True时可重复抽样，为false不能
c2=nr.choice(a,size=(3,3),replace=False)
c3=nr.choice(a,size=(3,3),p=a/np.sum(a))#p参数指定每个元素抽取的概率，下面值越大选取的概率越大

In [37]:
c1

array([[ 21.,  21.,  23.],
       [ 20.,  21.,  19.],
       [ 18.,  20.,  14.]])

In [38]:
c2

array([[ 12.,  19.,  10.],
       [ 15.,  17.,  13.],
       [ 24.,  11.,  20.]])

In [39]:
c3

array([[ 20.,  17.,  16.],
       [ 19.,  11.,  11.],
       [ 19.,  13.,  10.]])

In [40]:
c3

array([[ 20.,  17.,  16.],
       [ 19.,  11.,  11.],
       [ 19.,  13.,  10.]])

# 求和，平均值，方差

In [45]:
a=np.random.randint(0,20,size=(4,4))
np.sum(a)

113

In [46]:
a

array([[10,  7,  6, 18],
       [10, 10,  3,  7],
       [ 2,  1, 11,  5],
       [ 1,  0, 11, 11]])

In [47]:
np.sum(a)

113

In [48]:
sum(a)#每一列相加

array([23, 18, 31, 41])

In [49]:
np.sum(a,axis=0)#每一列数字相加

array([23, 18, 31, 41])

In [54]:
np.sum(a,axis=1)#每一行数字相加

array([41, 30, 19, 23])

In [55]:
np.mean(a)

7.0625

In [57]:
np.mean(a,axis=1)

array([ 10.25,   7.5 ,   4.75,   5.75])

In [60]:
np.set_printoptions(precision=8)
b=np.full(1000000,1.1,dtype=np.float32)

In [61]:
b

array([ 1.10000002,  1.10000002,  1.10000002, ...,  1.10000002,
        1.10000002,  1.10000002], dtype=float32)

In [62]:
np.mean(b)

1.0999993

In [63]:
np.mean(b,dtype=np.double)

1.1000000238418579

In [67]:
s=np.array([70,80,90])#average()函数计算加权平均数
n=np.array([10,20,2])
print(np.average(s,weights=n))

77.5


In [4]:
from numpy import random as nr
import numpy as np
a=nr.normal(0,2.0,(100000,10))
v1=np.var(a,axis=1,ddof=0)#var()函数是求方差函数，ddof=0时是偏样本方差`，=1时是无偏样本方差
v2=np.var(a,axis=1,ddof=1)#默认情况下ddof为0，不用写

In [5]:
v1

array([ 5.88786856,  2.66924286,  4.35124966, ...,  2.88019699,
        2.67187983,  2.80456108])

In [6]:
v2

array([ 6.54207618,  2.96582539,  4.83472185, ...,  3.20021888,
        2.96875537,  3.11617898])

In [7]:
np.mean(v1)

3.5943419818387792

In [8]:
np.mean(v2)

3.9937133131541986

# 大小与排列
min：最小值

max：最大值

minimum：二元最小值

maximum：二元最大值

ptp：最大值与最小值的差

argmin：最小值的下标

argmax：最大值的下标

unravel—index：一维下标转化为多维下标

sort：数组排列

argsort：计算数组排列的下标

lexsort：多位排列

partition：快速计算前三位

argpatition：前k位的下标

median：中位数

percentile：百分位数

searchsorted：二分查找
