一维插值逼近

In [3]:
import numpy as np#质量矩阵
def M(x):
    n=len(x)-1
    M=np.zeros((n+1,n+1))
    for i in range(n):
        h=1/n
        M[i,i]=M[i,i]+h/3
        M[i,i+1]=M[i,i+1]+h/6
        M[i+1,i]=M[i+1,i]+h/6
        M[i+1,i+1]=M[i+1,i+1]+h/3
    return M

In [4]:
print(M(np.linspace(0,1,6)))

[[ 0.06666667  0.03333333  0.          0.          0.          0.        ]
 [ 0.03333333  0.13333333  0.03333333  0.          0.          0.        ]
 [ 0.          0.03333333  0.13333333  0.03333333  0.          0.        ]
 [ 0.          0.          0.03333333  0.13333333  0.03333333  0.        ]
 [ 0.          0.          0.          0.03333333  0.13333333  0.03333333]
 [ 0.          0.          0.          0.          0.03333333  0.06666667]]


In [5]:
#载荷向量
def b(x,f):
    n=len(x)-1
    b=np.zeros((n+1,1))
    for i in range(n):
        h=x[i+1]-x[i]
        b[i]=b[i]+f[i]*h/2
        b[i+1]=b[i+1]+f[i+1]*h/2
    return b

In [6]:
def f(x):
    return x*np.sin(x)

In [7]:
f=f(np.linspace(0,1,6))
print(f)

[ 0.          0.03973387  0.15576734  0.33878548  0.57388487  0.84147098]


In [8]:
print(b(np.linspace(0,1,6),f))

[[ 0.        ]
 [ 0.00794677]
 [ 0.03115347]
 [ 0.0677571 ]
 [ 0.11477697]
 [ 0.0841471 ]]


In [9]:
W=np.linalg.inv(M(np.linspace(0,1,6)))#求逆

In [13]:
W

array([[ 17.32057416,  -4.64114833,   1.24401914,  -0.33492823,
          0.09569378,  -0.04784689],
       [ -4.64114833,   9.28229665,  -2.48803828,   0.66985646,
         -0.19138756,   0.09569378],
       [  1.24401914,  -2.48803828,   8.70813397,  -2.34449761,
          0.66985646,  -0.33492823],
       [ -0.33492823,   0.66985646,  -2.34449761,   8.70813397,
         -2.48803828,   1.24401914],
       [  0.09569378,  -0.19138756,   0.66985646,  -2.48803828,
          9.28229665,  -4.64114833],
       [ -0.04784689,   0.09569378,  -0.33492823,   1.24401914,
         -4.64114833,  17.32057416]])

In [14]:
b=b(np.linspace(0,1,6),f)
b

array([[ 0.        ],
       [ 0.00794677],
       [ 0.03115347],
       [ 0.0677571 ],
       [ 0.11477697],
       [ 0.0841471 ]])

In [16]:
c=np.dot(W,b)

In [18]:
np.sqrt(np.sum((f-c)*2,axis=0)

SyntaxError: unexpected EOF while parsing (<ipython-input-18-434c65bc7a9b>, line 1)

一维刚度矩阵

In [1]:
import numpy as np
def StiffnessAssembler(x):
    n=len(x)-1
    A=np.zeros((n+1,n+1))
    for i in range(n):
        h=1/5
        A[i,i]=A[i,i]+1/h
        A[i,i+1]=A[i,i+1]-1/h
        A[i+1,i]=A[i+1,i]-1/h
        A[i+1,i+1]=A[i+1,i+1]+1/h
    return A

In [2]:
A=StiffnessAssembler(np.linspace(0,1,6))
print(A)

[[  5.  -5.   0.   0.   0.   0.]
 [ -5.  10.  -5.   0.   0.   0.]
 [  0.  -5.  10.  -5.   0.   0.]
 [  0.   0.  -5.  10.  -5.   0.]
 [  0.   0.   0.  -5.  10.  -5.]
 [  0.   0.   0.   0.  -5.   5.]]


In [3]:
#载荷向量
def b(x,f):
    n=len(x)-1
    b=np.zeros((n+1,1))
    for i in range(n):
        h=x[i+1]-x[i]
        b[i]=b[i]+f*h/2
        b[i+1]=b[i+1]+f*h/2
    return b

In [4]:
b=b(np.linspace(0,1,6),2)
b

array([[ 0.2],
       [ 0.4],
       [ 0.4],
       [ 0.4],
       [ 0.4],
       [ 0.2]])

In [6]:
C=np.linalg.inv(A)
u=np.dot(A,b)
print(u)

LinAlgError: Singular matrix

In [10]:
def u(x):
    return x-x*x

In [11]:
x=np.linspace(0,1,6)
x

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [12]:
U=u(x)

In [19]:
np.sqrt(np.sum((U-u)*2,axis=0)

SyntaxError: unexpected EOF while parsing (<ipython-input-19-e7985eecba29>, line 1)