### <center>Python实验报告</center>
### <center>姓名：龚欣     $~~~~~~~~~$     学号：201821511222  </center>
### 实验题目：用列选主元初等行变换求矩阵的逆

### 实现算法：

1.选列主元，进行行变换，将绝对值最大值放在对角线位置，同时单位矩阵E做相同变换

2.进行初等行变换，将A化为上三角矩阵，同时E矩阵做相同变换

3.再从右下角往上将A化为对角矩阵，同时E矩阵也做相同变换 

4.将对角线化成1，即将A化为单位阵，同时E矩阵做相同变换，此时的E就是我们要求的A的逆
### 程序代码：

In [1]:
import numpy as np
def inver(A):
    
    n = len(A)
    E=np.eye(n,n)
    
    for i in range(n - 1):
        m = np.argmax(np.abs(A[i:, i])) + i              #找出每一列绝对值最大值的行指标
        if A[m, i] == 0:                                           #判断A是否奇异
            raise ValueError("matrix is singular.")
        else:
            if m != i:                                             
                A[[i, m], :] = A[[m, i], :]
                E[[i, m], :] = E[[m, i], :]
            
    #将A化为上三角矩阵     
            for j in range(i+1,n):  
                E[j,:]-=(A[j,i]/A[i,i])*E[i,:]        
                A[j,:]-=(A[j,i]/A[i,i])*A[i,:]            
                
    #将A化为对角矩阵           
    for q in range(n-1,0,-1): 
        for o in range(n-1,q-1,-1):
            E[q-1,:]-=(A[q-1,o]/A[o,o])*E[o,:]
            A[q-1,:]-=(A[q-1,o]/A[o,o])*A[o,:]

    #将A化为单位阵
    for p in range(n):
        E[p,:]=(1/A[p,p])*E[p,:]
        A[p,:]=(1/A[p,p])*A[p,:]
    return E

In [2]:
A=np.array([[1, 2, 3,3],
       [5, 5, 6,2],
       [6, 8, 9,5],
       [2,3,4,5]],np.float64)
A

array([[ 1.,  2.,  3.,  3.],
       [ 5.,  5.,  6.,  2.],
       [ 6.,  8.,  9.,  5.],
       [ 2.,  3.,  4.,  5.]])

In [3]:
B=np.linalg.inv(A)#python自带求矩阵的逆
B

array([[-0.88235294,  0.58823529, -0.41176471,  0.70588235],
       [-1.        , -1.        ,  1.        ,  0.        ],
       [ 1.70588235,  0.52941176, -0.47058824, -0.76470588],
       [-0.41176471, -0.05882353, -0.05882353,  0.52941176]])

In [4]:
C=inver(A)
C

array([[-0.88235294,  0.58823529, -0.41176471,  0.70588235],
       [-1.        , -1.        ,  1.        , -0.        ],
       [ 1.70588235,  0.52941176, -0.47058824, -0.76470588],
       [-0.41176471, -0.05882353, -0.05882353,  0.52941176]])

In [5]:
np.allclose(B,C)#判断矩阵B和C是否相近

True

In [9]:
np.max(np.abs(B-C))

6.106226635438361e-16

### 实验结果：
我们通过行变换求的逆与我们python自带求逆的误差非常小，因此此算法比较精确。